service: serverless-bolt-js
frameworkVersion: '3'
useDotenv: true


custom:
  esbuild:
    minify: true
    external:
      - 'argon2'
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['src/**/*.ts'] # default .
      ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']


provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    TURSO_API_TOKEN: ${env:TURSO_API_TOKEN}
    DATABASE_URL: ${env:DATABASE_URL} 
    DATABASE_AUTH_TOKEN: ${env:DATABASE_AUTH_TOKEN}
functions:
  slack:
    handler: src/lambda.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline